### ISSUE TITLE
有关所有的kawaii错误信息~^_^

### ISSUE THREAD

**Issue by CuteYuzu** [Bill-Haku/kawaii-gcc#13]
哈喽哈喽~我在B站看到了你的视频，感觉这个项目很有意思，专门下载试用了一下，确实很有趣！可以提供一下所有表述gcc错误台词的来源吗？我要参考这些东西来做我们小组的课程项目(Shell解释器）作为我们的亮点，并想沿用到这个项目相关的错误信息上~
非常感谢喵~（p.s. 这个项目真的非常不错，已经加星标啦~）

**Comment by Bill-Haku** [comment]
http://translationproject.org/domain/gcc.html
