### ISSUE TITLE
请问clion中还是为英文怎么弄

### ISSUE THREAD

**Issue by Aloys233** [Bill-Haku/kawaii-gcc#19]
clion好像用的cmake，但是我又是选择的gcc
<img width="461" alt="image" src="https://github.com/Bill-Haku/kawaii-gcc/assets/79312288/4b8e4a6a-71ac-4317-8cf9-0f901bf04780">

**Comment by Bill-Haku** [comment]
我没有研究过Windows。我帮你at一下贡献了windows使用方法的 @sishuikaki

**Comment by sishuikaki** [comment]
你尝试一下手动指定，如果没有make，需要在setup-x86_64.exe安装make
![image](https://github.com/Bill-Haku/kawaii-gcc/assets/123446578/7f6c6850-e027-4077-bd91-dfe722e61697)

**Comment by Aloys233** [comment]
感谢，方法没问题，中文也不乱码
