### ISSUE TITLE
Request for updating the project description

### ISSUE THREAD

**Issue by lhmouse** [Bill-Haku/kawaii-gcc#2]
I propose a change of

> GCCコンパイルを可愛くします。Make your GCC compiler kawaii.

to 

> GCCコンパイラーを可愛くしましょう！Make your GCC compiler kawaii!

**Comment by sakimidare** [comment]
May 可愛くなりましょう be better?

**Comment by lhmouse** [comment]
> May 可愛くなりましょう be better?

That would mean 'GCC, become cute' as if you were talking to it, in a very polite and weird way.

Compare: GCC、可愛くなれ！

**Comment by Bill-Haku** [comment]
> GCCコンパイラーを可愛くしましょう！

It LGTM. Thx for your suggestion
