### ISSUE TITLE
merge-zh.sh 这个文件在哪？？？？

### ISSUE THREAD

**Issue by Moonfanz** [Bill-Haku/kawaii-gcc#20]

**Comment by dabao1955** [comment]
该文件在#18 中被移除，实际上应该运行 make merge-zh :
https://github.com/Bill-Haku/kawaii-gcc/blob/main/Makefile

**Comment by Moonfanz** [comment]
![Z%`N8YVSMS762BK122I0QME](https://github.com/Bill-Haku/kawaii-gcc/assets/134288642/110a8595-174a-43e6-b0d5-6533b1982fe4)
c/c-parser.cc文件在哪？添加更多翻译的话需要知道它对应这个文件的第几行吧。

**Comment by Bill-Haku** [comment]
这是gcc的源代码里的文件。不过跟这里没有关系，我也不知道为什么简体中文的原版里会出现这些东西

**Comment by Moonfanz** [comment]
![image](https://github.com/Bill-Haku/kawaii-gcc/assets/134288642/d8a18c26-b7b9-4d25-b356-612eb04796e6)

![image](https://github.com/Bill-Haku/kawaii-gcc/assets/134288642/2ff71a9a-7053-43f1-a77b-fab60edbf34f)
怎么翻译这个expected ‘,’ or ‘;’ before ‘c’，我不知道c要用什么占位符

**Comment by Moonfanz** [comment]
已解决，c为 %qE
