### ISSUE TITLE
About Transilation

### ISSUE THREAD

**Issue by Dimanoti** [Bill-Haku/kawaii-gcc#3]
比如 
"笨蛋！invalid conversion from ‘int*’ to ‘int’ [-fpermissive]"
“笨蛋！expected unqualified-id before ‘{’ token”
"笨蛋！invalid preprocessing directive #dehhh"
“杂鱼～格式 ‘%d’ expects argument of type ‘int*’, but argument 2 has type ‘int’ [-Wformat=]”

另外建议编译成功也提示一下

**Comment by Bill-Haku** [comment]
有些是原本就没翻译的。总之你可以fork一份自己改就好了。

**Comment by Moe-hacker** [comment]
貌似翻译本身不全………建议从GCC最新的版本里搞一份中文翻译合并下再说。

**Comment by Bill-Haku** [comment]
原本本来翻译了的就三分之一都没到，你可以看[这里](http://translationproject.org/domain/gcc.html)

**Comment by Moe-hacker** [comment]
> 原本本来翻译了的就三分之一都没到，你可以看[这里](http://translationproject.org/domain/gcc.html)

我合并了下gcc上游的中文翻译，要pr吗？

**Comment by Bill-Haku** [comment]
你可以提一个PR看看

**Comment by dabao1955** [comment]
> > 原本本来翻译了的就三分之一都没到，你可以看[这里](http://translationproject.org/domain/gcc.html)
> 
> 我合并了下gcc上游的中文翻译，要pr吗？

~~这不得整个ja_JP~~

**Comment by Bill-Haku** [comment]
最初的默认的没有后缀的`gcc.po`就是ja_JP版
