### ISSUE TITLE
在CentOS 7 上配置失败

### ISSUE THREAD

**Issue by luo-xingyu** [Bill-Haku/kawaii-gcc#7]
使用虚拟机在ubuntu上配置成功了，在CentOS 7 上失败了，原因可能是在sudo apt-get install gcc-12-locales这一步，我的gcc版本是gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5) 我该如何解决？

**Comment by Bill-Haku** [comment]
7.3.1可能太老了不太一样，你可以先找找如何更换gcc的语言，然后还是覆盖`mo`文件
