### ISSUE TITLE
revert #4

### ISSUE THREAD

**Issue by Moe-hacker** [Bill-Haku/kawaii-gcc#8]
事实证明pr #4 有问题，请求撤回。。。

**Comment by Moe-hacker** [comment]
> 事实证明pr #4 有问题，请求撤回。。。

貌似其实是上游的问题。。。。
还有就是，建议把二次元化的内容单独存放在一个文件，最后生成mo文件时再合并为完整的，现在这样很难维护。

**Comment by dabao1955** [comment]
> > 事实证明pr #4 有问题，请求撤回。。。
> 
> 貌似其实是上游的问题。。。。 还有就是，建议把二次元化的内容单独存放在一个文件，最后生成mo文件时再合并为完整的，现在这样很难维护。

~~那么问题来了:像我直接修改gcc-zh.po的应该怎么办，而且改动比较大的那种~~
![Screenshot_2023-11-22-23-58-23-20_84d3000e3f4017145260f7618db1d683](https://github.com/Bill-Haku/kawaii-gcc/assets/79307765/eca4e5f4-e611-4f56-bab3-63896405c4c2)

**Comment by Bill-Haku** [comment]
> 还有就是，建议把二次元化的内容单独存放在一个文件，最后生成mo文件时再合并为完整的，现在这样很难维护。

可以考虑，我明天整理一下文件再重新PR

**Comment by Moe-hacker** [comment]
> > > 事实证明pr #4 有问题，请求撤回。。。
> > 
> > 
> > 貌似其实是上游的问题。。。。 还有就是，建议把二次元化的内容单独存放在一个文件，最后生成mo文件时再合并为完整的，现在这样很难维护。
> 
> ~那么问题来了:像我直接修改gcc-zh.po的应该怎么办，而且改动比较大的那种~ ![Screenshot_2023-11-22-23-58-23-20_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/79307765/284964630-eca4e5f4-e611-4f56-bab3-63896405c4c2.jpg)


遇事不决写段bash：
```bash
git diff c86517f | grep "+msgstr" | grep -v "@@" | sed -e "s/+msgstr/msgstr/g" >1
cat 1 | while read i; do
        x=$(cat gcc-zh.po | grep -n "$i" | cut -d ":" -f 1 | head -n 1)
        cat gcc-zh.po | awk "NR==$((x - 2))"
        cat gcc-zh.po | awk "NR==$((x - 1))"
        cat gcc-zh.po | awk "NR==$x"
done
```
另外，原版的中文翻译也有很多问题，最好自己修一下。

**Comment by dabao1955** [comment]
> > > > 事实证明pr #4 有问题，请求撤回。。。
> > > 
> > > 
> > > 貌似其实是上游的问题。。。。 还有就是，建议把二次元化的内容单独存放在一个文件，最后生成mo文件时再合并为完整的，现在这样很难维护。
> > 
> > 
> > ~那么问题来了:像我直接修改gcc-zh.po的应该怎么办，而且改动比较大的那种~ ![Screenshot_2023-11-22-23-58-23-20_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/79307765/284964630-eca4e5f4-e611-4f56-bab3-63896405c4c2.jpg)
> 
> 遇事不决写段bash：
> 
> ```shell
> git diff c86517f | grep "+msgstr" | grep -v "@@" | sed -e "s/+msgstr/msgstr/g" >1
> cat 1 | while read i; do
>         x=$(cat gcc-zh.po | grep -n "$i" | cut -d ":" -f 1 | head -n 1)
>         cat gcc-zh.po | awk "NR==$((x - 2))"
>         cat gcc-zh.po | awk "NR==$((x - 1))"
>         cat gcc-zh.po | awk "NR==$x"
> done
> ```
> 
> 另外，原版的中文翻译也有很多问题，最好自己修一下。

寄了:
 ```
u0_a1431@localhost ~> git clone https://github.com/Bill-Haku/kawaii-gcc/ 2
Cloning into '2'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 40 (delta 17), reused 33 (delta 11), pack-reused 0
Receiving objects: 100% (40/40), 629.30 KiB | 1.45 MiB/s, done.
Resolving deltas: 100% (17/17), done.
u0_a1431@localhost ~> cd 2
u0_a1431@localhost ~/2 (main)> ls
LICENSE  README-zh.md  README.md  gcc-zh.po  gcc.po  test.cc
u0_a1431@localhost ~/2 (main)> cp ../kawaii-gcc/gcc-zh.po ./
u0_a1431@localhost ~/2 (main)> cp ../kawaii-gcc/sync.sh ./
u0_a1431@localhost ~/2 (main)> bash sync.sh >./diff.txt
fatal: ambiguous argument 'c86517f': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
u0_a1431@localhost ~/2 (main)> git checkout c86517f
error: pathspec 'c86517f' did not match any file(s) known to git
u0_a1431@localhost ~/2 (main) [1]>
 ```

**Comment by Moe-hacker** [comment]
> > > > > 事实证明pr #4 有问题，请求撤回。。。
> > > > 
> > > > 
> > > > 貌似其实是上游的问题。。。。 还有就是，建议把二次元化的内容单独存放在一个文件，最后生成mo文件时再合并为完整的，现在这样很难维护。
> > > 
> > > 
> > > ~那么问题来了:像我直接修改gcc-zh.po的应该怎么办，而且改动比较大的那种~ ![Screenshot_2023-11-22-23-58-23-20_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/79307765/284964630-eca4e5f4-e611-4f56-bab3-63896405c4c2.jpg)
> > 
> > 遇事不决写段bash：
> > 
> > ```shell
> > git diff c86517f | grep "+msgstr" | grep -v "@@" | sed -e "s/+msgstr/msgstr/g" >1
> > cat 1 | while read i; do
> >         x=$(cat gcc-zh.po | grep -n "$i" | cut -d ":" -f 1 | head -n 1)
> >         cat gcc-zh.po | awk "NR==$((x - 2))"
> >         cat gcc-zh.po | awk "NR==$((x - 1))"
> >         cat gcc-zh.po | awk "NR==$x"
> > done
> > ```
> > 
> > 另外，原版的中文翻译也有很多问题，最好自己修一下。
> 
> 寄了:
>  ```
> u0_a1431@localhost ~> git clone https://github.com/Bill-Haku/kawaii-gcc/ 2
> Cloning into '2'...
> remote: Enumerating objects: 40, done.
> remote: Counting objects: 100% (40/40), done.
> remote: Compressing objects: 100% (28/28), done.
> remote: Total 40 (delta 17), reused 33 (delta 11), pack-reused 0
> Receiving objects: 100% (40/40), 629.30 KiB | 1.45 MiB/s, done.
> Resolving deltas: 100% (17/17), done.
> u0_a1431@localhost ~> cd 2
> u0_a1431@localhost ~/2 (main)> ls
> LICENSE  README-zh.md  README.md  gcc-zh.po  gcc.po  test.cc
> u0_a1431@localhost ~/2 (main)> cp ../kawaii-gcc/gcc-zh.po ./
> u0_a1431@localhost ~/2 (main)> cp ../kawaii-gcc/sync.sh ./
> u0_a1431@localhost ~/2 (main)> bash sync.sh >./diff.txt
> fatal: ambiguous argument 'c86517f': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> u0_a1431@localhost ~/2 (main)> git checkout c86517f
> error: pathspec 'c86517f' did not match any file(s) known to git
> u0_a1431@localhost ~/2 (main) [1]>
>  ```

在你自己fork的仓库里运行，这段bash会自动找出你翻译过的msgid和msgstr，然后稍作修改就行了………………
